language: android
sudo: false

jdk:
  - oraclejdk8

android:
  components:
    - tools
    - platform-tools
    - build-tools-27.0.2
    - android-27
    - extra-android-m2repository
    - extra-google-m2repository

branches:
  except:
  - /^v\d$/

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle

before_script:
  - chmod +x gradlew

script:
  - ./gradlew build

after_success:
  - ./bash <(curl -s https://codecov.io/bash)

deploy:
  - provider: script
    script: ./gradlew ciPerformRelease -s
    skip_cleanup: true
    on:
      branch: master

notifications:
  email: false
